import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/navbar/Navbar";
import Image from "next/image";
import bg from "../assets/bg.png";
import Breadcrumbs from "../components/breadcrumbs/Breadcrumbs";
import { AuthProvider } from "@/components/breadcrumbs/context/AuthContext";
import ToastProvider from "@/components/Toast/ToastProvider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <AuthProvider>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div className="bg-radial from-blue-950 to-black h-screen w-screen -z-10 fixed top-0">
          <div className="bg-yellow"></div>
        </div>
        <Navbar></Navbar>
        <div className="p-10">
          <Breadcrumbs />

            <ToastProvider>{children}</ToastProvider>
        </div>
      </body>
          </AuthProvider>
    </html>
  );
}
