name: Deploy Vercel Preview

on:
  pull_request:
    branches:
      - main  # Change if your default branch is different

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install Vercel CLI
        run: npm install -g vercel

      - name: Deploy to Vercel
        run: |
          vercel pull --yes --environment=preview --token=${{ secrets.VERCEL_TOKEN }}
          vercel deploy --prebuilt --token=${{ secrets.VERCEL_TOKEN }}
      - name: Comment on PR with Vercel Preview URL
              uses: thollander/actions-comment-on-pr@v2
              with:
                message: "🚀 Preview deployed! [View Preview](${{ env.DEPLOY_URL }})"
                GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}