name: Deploy Vercel Preview

on:
  pull_request:
    branches:
      - main  # Change if your default branch is different

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install Vercel CLI
        run: npm install -g vercel

      - name: Deploy to Vercel
        run: |
          vercel pull --yes --environment=preview --token=${{ IM7CCkXyw0UW0BkEJet5GEro }}
          vercel deploy --prebuilt --token=${{ IM7CCkXyw0UW0BkEJet5GEro }}
